# Fondamentaux de NumPy

## Qu'est-ce que NumPy ?

NumPy (Numerical Python) est une bibliothèque Python open source qui contient des tableaux multidimensionnels et des structures de données matricielles, et fournit des ndarray, un tableau homogène à n dimensions, avec des méthodes permettant de l'exploiter efficacement. 
Il existe plusieurs différences importantes entre les tableaux NumPy et les tableaux Python standard :
Les tableaux NumPy ont une taille fixe à la création, contrairement aux listes Python (dynamique). Changer la taille d'un tableau NumPy va créer un nouveau tableau et supprimer l'original.
Les éléments d'un tableau NumPy doivent tous être du même type de données, et auront donc la même taille en mémoire. 
Les tableaux NumPy facilitent les opérations mathématiques avancées et d'autres types d'opérations sur de grands nombres de données. En général, ces opérations sont exécutées plus efficacement et avec moins de code que Python.

## Pourquoi utiliser NumPy ?

Les tableaux NumPy sont plus rapides et plus compacts que les listes Python. Un tableau consomme moins de mémoire et est pratique à utiliser. NumPy utilise beaucoup moins de mémoire pour stocker les données et il fournit un mécanisme permettant de spécifier les types de données. Cela permet d'optimiser encore plus le code.
## Qu'est-ce qu'un tableau NumPy ?
Un tableau est une structure de données centrale de la bibliothèque NumPy. Un tableau est une grille de valeurs et il contient des informations sur les données brutes, sur la façon de localiser un élément et sur la façon d'interpréter un élément. Il possède une grille d'éléments qui peuvent être indexés de différentes manières. Les éléments sont tous du même type, appelé le dtype du tableau.
Un tableau peut être indexé par un tuple d'entiers non négatifs, par des booléens, par un autre tableau ou par des entiers. Le rang du tableau est le nombre de dimensions. La forme du tableau est un tuple d'entiers donnant la taille du tableau pour chaque dimension.

## Importation de NumPy

NumPy est généralement importé sous l'alias np. alias : En Python, les alias sont un nom alternatif pour se référer à la même chose. Créez un alias avec le mot-clé as lors de l'importation :

Exemple:

In [2]:
import numpy as np

Désormais, le paquet NumPy peut être désigné par np au lieu de numpy.

## Création d'un objet NumPy: ndarray

NumPy est utilisé pour travailler avec des tableaux. L'objet tableau dans NumPy est appelé ndarray. On peut créer un objet NumPy ndarray en utilisant la fonction array()

Exemple

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): Cette fonction Python intégrée nous indique le type de l'objet qui lui est passé. Comme dans le code ci-dessus, elle montre que arr est de type numpy.ndarray.

Pour créer un ndarray, nous pouvons passer une liste, un tuple ou tout autre objet de type tableau dans la méthode array(), et il sera converti en ndarray:

Exemple : Utiliser un tuple pour créer un tableau NumPy :

In [4]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


## Dimensions des tableaux

Une dimension dans les tableaux est un niveau de profondeur de tableau (tableaux imbriqués).

Les tableaux imbriqués sont des tableaux dont les éléments sont des tableaux.

### Tableaux 0-D

Les tableaux 0-D, ou scalaires, sont les éléments du tableau.



Exemple

Créer un tableau 0-D avec la valeur 25

In [2]:
import numpy as np

arr = np.array(25)

print(arr)

25


### Tableaux 1-D

Un tableau dont les éléments sont des tableaux 0-D est appelé tableau unidimensionnel ou 1-D. Il s'agit des tableaux les plus courants et les plus élémentaires.

Ce sont les tableaux les plus courants et les plus basiques.

Exemple
Créez un tableau 1-D contenant les valeurs 1,2,3,4,5 :

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Tableaux 2-D

Un tableau dont les éléments sont des tableaux 1-D s'appelle un tableau 2-D.

Ils sont souvent utilisés pour représenter des matrices ou des tenseurs d'ordre 2.

NumPy possède un sous-module entier dédié aux opérations matricielles appelé numpy.mat.

Exemple
Créer un tableau 2-D contenant deux tableaux avec les valeurs 1,2,3 et 4,5,6 :

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### Tableaux 3-D

Un tableau dont les éléments sont des tableaux 2-D (matrices) est appelé tableau 3-D.

Ils sont souvent utilisés pour représenter un tenseur d'ordre 3.

Exemple
Créez un tableau 3-D avec deux tableaux 2-D, contenant chacun deux tableaux avec les valeurs 1,2,3 et 4,5,6 :

In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### Vérifiez le nombre de dimensions

NumPy Arrays fournit l'attribut ndim qui renvoie un entier qui nous indique le nombre de dimensions du tableau.

Exemple

Vérifiez combien de dimensions ont les tableaux :

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Tableaux de dimensions supérieures

Un tableau peut avoir un nombre quelconque de dimensions.

Lorsque le tableau est créé, vous pouvez définir le nombre de dimensions en utilisant l'argument ndmin.

Exemple

Créez un tableau à 5 dimensions et vérifiez qu'il a 5 dimensions :

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Constructeurs de tableaux Numpy

Il existe plusieurs manières pour créer des tableaux en utilisant numpy, à savoir : 
- **array** : Crée un tableau.
- **eye** : Retourne un tableau 2-D avec des uns sur la diagonale et des zéros ailleurs.
- **ones** : Retourne un nouveau tableau rempli de uns.
- **zeros** : Renvoie un nouveau tableau rempli de zéros.
- **full** : Retourne un nouveau tableau rempli avec la valeur de remplissage passée en paramètre.
- **arange(i, j, p)** : permet de créer un array rempli avec une séquence linéaire, qui ira de  i  à  j, par pas de  p
- **linspace(i, j, n)** : permet de créer un array de  n  valeurs espacées uniformément entre  i  et  j.
- **random.randn(m, n)** : retourne un tableau aléatoire (à distribution normale) aux dimensions m x n
- **random.rand(m, n)** : retourne un tableau aléatoire (distribution uniforme)  aux dimensions m x n
- **random.randint(i, j, [m, n])** : retourne un tableau d'entiers aléatoires allant de i jusqu'à j et de dimension m x n

In [9]:
import numpy as np
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
import numpy as np
un = np.ones((2, 6, 5))
un

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
import numpy as np
zéro = np.zeros((2, 3))
zéro

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
import numpy as np
p = np.full((4, 6), 5)
p

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [1]:
import numpy as np
a = np.arange(0, 100, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [2]:
import numpy as np
l = np.linspace(5, 60, 10)
l

array([ 5.        , 11.11111111, 17.22222222, 23.33333333, 29.44444444,
       35.55555556, 41.66666667, 47.77777778, 53.88888889, 60.        ])

In [7]:
C = np.random.randn(2, 3)
D = np.random.rand(2, 3) 
E = np.random.randint(0, 10, [2, 3, 5])
print (C)
print (D)
print (E)

[[-0.65867936  1.48764587  0.86787832]
 [-1.23584034  0.40425473  0.29465063]]
[[0.24761284 0.12951898 0.58308133]
 [0.40711741 0.92757469 0.4798727 ]]
[[[9 3 4 0 4]
  [3 0 9 4 6]
  [9 3 3 5 2]]

 [[8 8 5 7 8]
  [5 5 4 2 0]
  [6 6 0 9 0]]]


# Types de données NumPy

## Types de données en Python
Par défaut, Python dispose de ces types de données :

-  string - utilisé pour représenter des données textuelles, le texte est donné entre guillemets. par exemple, "ABCD".
-  integer - utilisé pour représenter les nombres entiers. par exemple -1, -2, -3
-  float - utilisé pour représenter les nombres réels, par exemple 1,2, 42,42.
-  booléen - utilisé pour représenter Vrai ou Faux.
-  complexe - utilisé pour représenter les nombres complexes, par exemple 1,0 + 2,0j, 1,5 + 2,5j.

## Types de données dans NumPy
L'objet NumPy array possède une propriété appelée dtype qui renvoie le type de données du tableau :
#### Exemple
Obtenir le type de données d'un tableau :

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


#### Exemple
Obtenir le type de données d'un tableau contenant des chaînes de caractères :

In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Créer des tableaux avec un type de données défini

Nous utilisons la fonction array() pour créer des tableaux, cette fonction peut prendre un argument optionnel : dtype qui nous permet de définir le type de données attendu des éléments du tableau :

#### Exemple
Créer un tableau avec le type de données string :

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Pour i, u, f, S et U, nous pouvons également définir la taille.
#### Exemple
Créer un tableau avec le type de données 4 bytes integer :

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Conversion du type de données sur des tableaux existants
La meilleure façon de changer le type de données d'un tableau existant est de faire une copie du tableau avec la méthode astype().

La fonction astype() crée une copie du tableau, et vous permet de spécifier le type de données en tant que paramètre.

Le type de données peut être spécifié à l'aide d'une chaîne de caractères, comme 'f' pour float, 'i' pour integer etc. ou vous pouvez utiliser le type de données directement comme float pour float et int pour integer.

#### Exemple
Changez le type de données de float à integer en utilisant 'i' comme valeur de paramètre :

In [5]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


#### Exemple
Changer le type de données de float à integer en utilisant int comme valeur de paramètre :

In [7]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


#### Exemple
Changer le type de données d'un entier à un booléen :

In [8]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
