# Indexation des tableaux NumPy

## Accès aux éléments d'un tableau 

L'indexation d'un tableau est la même chose que l'accès à un élément du tableau.

Vous pouvez accéder à un élément d'un tableau en vous référant à son numéro d'index.

Les indices dans les tableaux NumPy commencent par 0, ce qui signifie que le premier élément a l'indice 0, et le second l'indice 1, etc.

#### Exemple
Obtenez le premier élément du tableau suivant :

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


#### Exemple
Obtenez les troisième et quatrième éléments du tableau suivant et ajoutez-les.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


## Accès aux éléments des tableaux 2-D

Pour accéder aux éléments des tableaux 2-D, nous pouvons utiliser des entiers séparés par des virgules représentant la dimension et l'index de l'élément.

Pensez aux tableaux 2-D comme à un tableau avec des lignes et des colonnes, où la ligne représente la dimension et l'index la colonne.

#### Exemple
Accédez à l'élément de la première ligne, deuxième colonne :

In [3]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


## Access 3-D Arrays

Pour accéder aux éléments des tableaux 3-D, nous pouvons utiliser des entiers séparés par des virgules représentant les dimensions et l'index de l'élément.

#### Exemple
Accédez au troisième élément du deuxième tableau du premier tableau :

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Indexation négative

Utilisez l'indexation négative pour accéder à un tableau depuis la fin.

#### Exemple

Imprimer le dernier élément de ce tableau 2D :

In [5]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('le dernier élément de ce tableau 2D est : ', arr[-1, -1])

le dernier élément de ce tableau 2D est :  10


# Découpage de tableaux NumPy

## Découpage d'un tableau 1D

Le découpage en tranches en python signifie prendre des éléments d'un indice donné à un autre indice donné.

On définit slice au lieu d'index comme ceci : [début : fin].

Nous pouvons également définir le pas, comme ceci : [début : fin : étape].

Si nous ne définissons pas le début, il est considéré comme 0.

Si nous ne définissons pas la fin, elle est considérée comme la longueur du tableau dans cette dimension.

Si nous ne définissons pas le pas, il est considéré comme égal à 1.

#### Exemple
Découpez les éléments de l'indice 1 à l'indice 5 du tableau suivant :

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


#### Exemple
Découpez les éléments de l'index 4 à la fin du tableau :

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


#### Exemple
Couper les éléments du début à l'indice 4 (non inclus) :

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


### Découpage négatif
Utilisez l'opérateur moins pour faire référence à un indice à partir de la fin :

#### Exemple
Trancher de l'indice 3 de la fin à l'indice 1 de la fin :

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### l'ÉTAPE
Utilisez la valeur de l'étape pour déterminer l'étape du découpage :

#### Exemple
Retourner un élément sur deux de l'indice 1 à l'indice 5 :

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


#### Exemple
Retourner un élément sur deux du tableau entier :

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


## Découpage de tableaux 2-D
#### Exemple
À partir du deuxième élément(càd l'indice 1), découpez les éléments de l'indice 1 à l'indice 4 (non inclus) :

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


#### Exemple
A partir des deux éléments, retourner l'indice 2 :

In [13]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print (arr[:, 2])

[3 8]


#### Exemple
A partir des deux éléments, de l'indice de tranche 1 à l'indice 4 (non inclus), ceci retournera un tableau 2-D :

In [14]:
import numpy as np
arr =np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[:, 1:4])

[[2 3 4]
 [7 8 9]]


#### Exemple :
Remplir le tableau suivant de "1" (une ligne sur deux, une colonne sur deux)

In [15]:
C = np.zeros((5, 5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
C = np.zeros((5, 5))
C [::2, ::2]=1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])