# Copie de tableau NumPy vs vue

## La différence entre copy et view
La principale différence entre une copie et une vue d'un tableau est que la copie est un nouveau tableau, et que la vue est juste une vue du tableau original.

La copie possède les données et toute modification apportée à la copie n'affectera pas le tableau original, et toute modification apportée au tableau original n'affectera pas la copie.

La vue ne possède pas les données et toute modification apportée à la vue affectera le tableau original, et toute modification apportée au tableau original affectera la vue.

## COPY :
#### Exemple
Faites une copie, modifiez le tableau original et affichez les deux tableaux:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
c = arr.copy()
arr[0] = 42

print(arr)
print(c)

[42  2  3  4  5]
[1 2 3 4 5]


La copie NE DOIT PAS être affectée par les modifications apportées au tableau d'origine.

## VIEW :
#### Exemple
Créez une vue, modifiez le tableau original et affichez les deux tableaux :

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
v = arr.view()
arr[0] = 42

print(arr)
print(v)

[42  2  3  4  5]
[42  2  3  4  5]


La vue DEVRAIT être affectée par les modifications apportées au tableau d'origine.

## Faire des changements dans la VIEW :
#### Exemple
Créez une vue, modifiez-la et affichez les deux tableaux :

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
v = arr.view()
v[0] = 31

print(arr)
print(v)

[31  2  3  4  5]
[31  2  3  4  5]


Le tableau original DEVRAIT être affecté par les modifications apportées à la vue.

## Vérifier si le tableau possède ses données
Comme mentionné ci-dessus, les copies possèdent les données, et les vues ne possèdent pas les données, mais comment pouvons-nous vérifier cela ?

Chaque tableau NumPy possède l'attribut base qui renvoie None si le tableau possède les données.

Sinon, l'attribut base fait référence à l'objet original.

#### Exemple
Imprimez la valeur de l'attribut base pour vérifier si un tableau possède ses données ou non :

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Forme et taille du tableau NumPy
## Obtenir la taille d'un tableau
L'attribut size renvoie le nombre d'élément constituant un tableau.
#### Exemple
Afficher la taille du tableau 2-D suivant :

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.size)

8


## Obtenir la forme d'un tableau
__Forme d'un tableau__ : La forme d'un tableau est le nombre d'éléments dans chaque dimension.

Les tableaux NumPy ont un attribut appelé shape qui renvoie un tuple avec chaque index ayant le nombre d'éléments correspondants.

#### Exemple
Affiche la forme d'un tableau 2-D :

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


L'exemple ci-dessus renvoie (2, 4), ce qui signifie que le tableau a 2 dimensions, où la première dimension a 2 éléments et la seconde 4.

#### Exemple
Créer un tableau à 5 dimensions en utilisant ndmin en utilisant un vecteur avec les valeurs 1,2,3,4 et vérifier que la dernière dimension a la valeur 4 :

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### Que représente le tuple de forme ?

Les nombres entiers à chaque index indiquent le nombre d'éléments de la dimension correspondante.

Dans l'exemple ci-dessus, à l'indice 4, nous avons la valeur 4, nous pouvons donc dire que la 5ème dimension (4 + 1) a 4 éléments.

### Squeeze
*numpy.squeeze* renvoie le tableau d'entrée, mais avec toutes ou un sous-ensemble des dimensions de longueur 1 enlevées.

In [3]:
x = np.array([[[0,1], [1,2], [2,3]]])
x.shape

(1, 3, 2)

In [5]:
x = np.array([[[0,1], [1,2], [2,3]]])
np.squeeze(x).shape

(3, 2)

# Réorganisation des tableaux NumPy

Le Réorganisation consiste à modifier la forme d'un tableau.

La forme d'un tableau est le nombre d'éléments dans chaque dimension.

En Réorganisation, nous pouvons ajouter ou supprimer des dimensions ou changer le nombre d'éléments dans chaque dimension.

## Réorganisation : de 1-D à 2-D
#### Exemple
Convertissez le tableau 1-D suivant avec 12 éléments en un tableau 2-D.

La dimension la plus extérieure comprendra 4 tableaux, chacun contenant 3 éléments :

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape de 1-D à 3-D
#### Exemple
Convertissez le tableau 1-D suivant avec 12 éléments en un tableau 3-D.

La dimension la plus externe aura 2 tableaux qui contiendront 3 tableaux, chacun avec 2 éléments :

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Peut-on remodeler dans n'importe quelle forme ?
__OUI__, tant que les éléments requis pour le remodelage sont égaux dans les deux formes.

Nous pouvons transformer un tableau 1D de 8 éléments en un tableau 2D de 4 éléments sur 2 rangées, mais nous ne pouvons pas le transformer en un tableau 2D de 3 éléments sur 3 rangées, car cela nécessiterait 3x3 = 9 éléments.

#### Exemple
Essayez de convertir un tableau 1D avec 8 éléments en un tableau 2D avec 3 éléments dans chaque dimension (cela provoquera une erreur) :

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,2,2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## On Retourne une Copie ou une Vue ?
#### Exemple
Vérifier si le tableau retourné est une copie ou une vue :

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


L'exemple ci-dessus renvoie le tableau original, il s'agit donc d'une vue.

## Dimension inconnue
Vous êtes autorisé à avoir une dimension "inconnue".

Cela signifie que vous n'avez pas à spécifier un nombre exact pour l'une des dimensions dans la méthode reshape.

Définissez -1 comme valeur, et NumPy calculera ce nombre pour vous.

#### Exemple
Convertir un tableau 1D de 8 éléments en un tableau 3D de 2x2 éléments:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 4, 2)

print(newarr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


__Note__ : On ne peut pas définir -1 pour plus d'une dimension.

## Aplatissement des tableaux
Aplatir un tableau signifie convertir un tableau multidimensionnel en un tableau 1D.

Nous pouvons utiliser reshape(-1) pour le faire.

#### Exemple
Convertir le tableau en un tableau 1D :

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


__Note__ : Il existe de nombreuses fonctions pour modifier la forme des tableaux dans numpy : *flatten, ravel* et aussi pour réarranger les éléments : *rot90, flip, fliplr, flipud*, etc. 

## Exemples de manipulations des tableaux Numpy
Executer les codes suivants pour comprendre le mode de fonctionnement des fonctions *flatten, ravel, flip, fliplr, flipud, et rot90*

In [2]:
import numpy as np
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(x)

array([[6, 5, 4],
       [3, 2, 1]])

In [5]:
A = np.diag([1.,2.,3.])
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

In [6]:
A = np.diag([1.0, 2, 3])
np.flipud(A)

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [7]:
m = np.array([[1,2],[3,4]])
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [8]:
x = np.array([[1.,2.],[3.,4.]])
x.T

array([[1., 3.],
       [2., 4.]])

# Itération d'un tableau NumPy
__Itération de tableaux (Iterating Arrays)__ : Itérer signifie parcourir les éléments un par un.

Comme nous traitons des tableaux multidimensionnels dans numpy, nous pouvons le faire en utilisant la boucle for de base de python.

Si nous itérons sur un tableau 1-D, chaque élément sera parcouru un par un.

#### Exemple
Itérer sur les éléments du tableau 1-D suivant :

In [15]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


## Itération de tableaux 2-D
Dans un tableau à deux dimensions, on parcourt toutes les lignes.

#### Exemple
Faites un itération sur les éléments du tableau 2-D suivant :

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


Si nous itérons sur un tableau n-D, il passera par la dimension n-1, une par une.

Pour retourner les valeurs réelles, les scalaires, nous devons itérer les tableaux dans chaque dimension.

#### Exemple
Itérer sur chaque élément scalaire du tableau 2-D :

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## Itération de tableaux 3-D
Dans un tableau 3-D, tous les tableaux 2-D sont parcourus.

#### Exemple
Effectuez un itération sur les éléments du tableau 3-D suivant :

In [18]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Pour retourner les valeurs réelles, les scalaires, nous devons itérer les tableaux dans chaque dimension.

#### Exemple
Itérer jusqu'aux scalaires :

In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Itération de tableaux avec nditer()
La fonction *nditer()* est une fonction d'aide qui peut être utilisée pour des itérations très basiques ou très avancées. Elle résout certains problèmes de base auxquels nous sommes confrontés dans l'itération, voyons cela avec des exemples.

### Itération sur chaque élément scalaire
Dans les boucles for de base, l'itération sur chaque scalaire d'un tableau nécessite l'utilisation de n boucles for, ce qui peut être difficile à écrire pour des tableaux de très grande dimension.

#### Exemple
Effectuez un itération dans le tableau 3-D suivant :

In [20]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Itération d'un tableau avec différents types de données
Nous pouvons utiliser l'argument op_dtypes et lui définir le type de données attendu pour changer le type de données des éléments pendant l'itération.

NumPy ne change pas le type de données de l'élément in-place (lorsque l'élément est dans le tableau), il a donc besoin d'un autre espace pour effectuer cette action, cet espace supplémentaire est appelé tampon, et afin de l'activer dans nditer() nous passons flags=['buffered'].
#### Exemple
Interroger le tableau en tant que chaîne de caractères :

In [21]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


## Itération avec différentes tailles de pas
Nous pouvons utiliser le filtrage suivi de l'itération.

#### Exemple
Itérer à travers chaque élément scalaire du tableau 2D en sautant 1 élément :

In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## Itération énumérée à l'aide de ndenumerate()
L'énumération consiste à mentionner le numéro de séquence de quelque chose un par un.

Parfois, nous avons besoin de l'index correspondant de l'élément lors de l'itération, la méthode ndenumerate() peut être utilisée pour ces cas d'utilisation.

#### Exemple
Enumérer les éléments suivants d'un tableau 1D :

In [23]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


#### Exemple
Énumérer les éléments du tableau 2D suivant :

In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy : jointure de tableaux

## Joindre des tableaux NumPy

La jointure consiste à mettre le contenu de deux tableaux ou plus dans un seul tableau.

En SQL, nous joignons des tableaux en fonction d'une clé, alors qu'en NumPy, nous joignons des tableaux par axes.

Nous passons une séquence de tableaux que nous voulons joindre à la fonction concatenate(), ainsi que l'axe. Si l'axe n'est pas défini explicitement, il est pris égal à 0.

#### Exemple
Joindre deux tableaux : 

In [33]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### Exemple
Joindre deux tableaux 2-D le long des lignes (axe=1) :

In [1]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joindre des tableaux en utilisant des fonctions de pile

L'empilage est identique à la concaténation, la seule différence étant que l'empilage est effectué le long d'un nouvel axe.

Nous pouvons concaténer deux tableaux 1-D le long du deuxième axe, ce qui revient à les placer l'un sur l'autre, c'est-à-dire à les empiler.

Nous passons une séquence de tableaux que nous voulons joindre à la méthode stack() avec l'axe. Si l'axe n'est pas défini explicitement, il est considéré comme égal à 0.

#### Exemple

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


## Empilement le long des lignes
NumPy fournit une fonction d'aide : hstack() pour empiler le long des lignes.

#### Exemple

In [30]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Empilement le long des colonnes
NumPy fournit une fonction d'aide : vstack() pour empiler le long des colonnes.

#### Exemple

In [31]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Empilement selon la hauteur (profondeur)
NumPy fournit une fonction d'aide : dstack() pour empiler selon la hauteur, qui est la même que la profondeur.

#### Exemple

In [32]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Fractionnement des tableaux NumPy
La division est l'opération inverse de la jonction.

La jointure fusionne plusieurs tableaux en un seul et la division divise un tableau en plusieurs.

Nous utilisons array_split() pour diviser les tableaux, nous lui définissons le tableau que nous voulons diviser et le nombre de divisions.

#### Exemple
Divise le tableau en 3 parties :

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


__Note__ : La valeur de retour est un tableau contenant trois tableaux.

Si le tableau a moins d'éléments que nécessaire, il sera ajusté à partir de la fin en conséquence.

#### Exemple
Divisez le tableau en 4 parties :

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


__Remarque__ : Nous avons également la méthode split() disponible mais elle n'ajustera pas les éléments quand il y a moins d'éléments dans le tableau source à diviser comme dans l'exemple ci-dessus, array_split() a fonctionné correctement mais split() a échoué.

## Diviser en tableaux
La valeur de retour de la méthode array_split() est un tableau contenant chacun des éléments divisés sous forme de tableau.

Si vous divisez un tableau en 3 tableaux, vous pouvez y accéder à partir du résultat comme n'importe quel élément de tableau :

#### Exemple
Accéder aux tableaux divisés :

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


## Fractionnement de tableaux 2-D
Utilisez la même syntaxe pour diviser les tableaux 2-D.

Utilisez la méthode array_split(), définissez le tableau que vous souhaitez diviser et le nombre de divisions que vous souhaitez effectuer.

#### Exemple
Divisez le tableau 2-D en trois tableaux 2-D.

In [6]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


L'exemple ci-dessus renvoie trois tableaux 2-D.

Voyons un autre exemple, cette fois-ci chaque élément des tableaux 2-D contient 3 éléments.

#### Exemple
Divisez le tableau 2-D en trois tableaux 2-D.

In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


L'exemple ci-dessus renvoie trois tableaux bidimensionnels.

En outre, vous pouvez spécifier l'axe autour duquel vous souhaitez effectuer la division.

L'exemple ci-dessous renvoie également trois tableaux 2-D, mais ils sont divisés le long de la ligne (axe=1).

#### Exemple
Divise le tableau 2-D en trois tableaux 2-D le long des lignes.

In [48]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Une solution alternative consiste à utiliser hsplit() à l'opposé de hstack()

#### Exemple
Utilisez la méthode hsplit() pour diviser le tableau 2-D en trois tableaux 2-D le long des lignes.

In [49]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


__Note__ : Des alternatives similaires à vstack() et dstack() sont disponibles en tant que vsplit() et dsplit().

# Recherche dans les tableaux de NumPy

## Recherche dans les tableaux
Vous pouvez rechercher une valeur donnée dans un tableau et renvoyer les index qui correspondent à cette valeur.

Pour rechercher dans un tableau, utilisez la méthode where().

#### Exemple
Trouvez les indices où les valeurs sont paires :

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


#### Exemple
Trouvez les indices où les valeurs sont impaires :

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


## Recherche triée
Il existe une méthode appelée searchsorted() qui effectue une recherche binaire dans le tableau, et renvoie l'index où la valeur spécifiée serait insérée pour maintenir l'ordre de recherche.

La méthode searchsorted() est supposée être utilisée sur des tableaux triés.

#### Exemple
Trouver les index où la valeur 7 doit être insérée pour maintenir l'ordre:

In [9]:
import numpy as np

arr = np.array([6, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


## Recherche à partir du côté droit
Par défaut, l'index le plus à gauche est renvoyé, mais nous pouvons donner side='right' pour renvoyer l'index le plus à droite à la place.

#### Exemple
Trouver les index où la valeur 7 doit être insérée, en commençant par la droite :

In [15]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8, side='right')

print(x)

3


## Valeurs multiples
Pour rechercher plusieurs valeurs, utilisez un tableau avec les valeurs spécifiées.

#### Exemple
Trouvez les index où les valeurs 2, 4 et 6 doivent être insérées :

In [55]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


Le résultat est un tableau : [1 2 3] contenant les trois index où 2, 4, 6 seraient insérés dans le tableau original pour maintenir l'ordre.

# Tri des tableaux

Trier signifie mettre des éléments dans une séquence ordonnée.

Une séquence ordonnée est une séquence qui a un ordre correspondant aux éléments, comme un ordre numérique ou alphabétique, ascendant ou descendant.

L'objet NumPy ndarray possède une fonction appelée sort(), qui permet de trier un tableau spécifié.

#### Exemple
Trier le tableau :

In [56]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


**Remarque** : Cette méthode renvoie une copie du tableau, laissant le tableau original inchangé.

Vous pouvez également trier des tableaux de chaînes de caractères, ou tout autre type de données :

#### Exemple
Triez le tableau par ordre alphabétique :

In [16]:
import numpy as np

arr = np.array(['banane', 'pomme', 'cerise'])

print(np.sort(arr))

['banane' 'cerise' 'pomme']


#### Exemple
Trier un tableau de booléens :

In [59]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


## Tri d'un tableau 2-D
Si vous utilisez la méthode sort() sur un tableau 2-D, les deux tableaux seront triés :

#### Exemple
Trier un tableau 2-D :

In [60]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Tableaux de filtrage

Extraire certains éléments d'un tableau existant et créer un nouveau tableau à partir de ces éléments est appelé filtrage.

Dans NumPy, on filtre un tableau en utilisant une liste d'index booléens.

Une liste d'index booléens est une liste de booléens correspondant à des index dans le tableau.

Si la valeur d'un index est Vrai, l'élément est contenu dans le tableau filtré, si la valeur de cet index est Faux, l'élément est exclu du tableau filtré.

#### Exemple
Créer un tableau à partir des éléments aux indices 0 et 2 :

In [61]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


## Création d'un tableau de filtres
Dans l'exemple ci-dessus, nous avons codé en dur les valeurs True et False, mais l'usage courant est de créer un tableau de filtres basé sur des conditions.

#### Exemple
Créez un tableau de filtres qui ne retournera que les valeurs supérieures à 42 :

In [62]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Créer une liste vide
filter_arr = []

# parcourir chaque élément du tableau arr
for element in arr:
  # si l'élément est supérieur à 42, donnez-lui la valeur True, sinon False :
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


## Créer un filtre directement à partir d'un tableau
L'exemple ci-dessus est une tâche assez courante dans NumPy et NumPy fournit une façon agréable de l'aborder.

Nous pouvons substituer directement le tableau à la place de la variable itérable dans notre condition et cela fonctionnera exactement comme nous l'attendons.

#### Exemple
Créez un tableau de filtres qui ne retournera que les valeurs supérieures à 42 :

In [1]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr² = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
