# Mathématique avec les tableaux NumPy

## Opérations arithmétiques de base sur les tableaux NumPy

In [1]:
import numpy as np
a = np.arange(1,6)
print('Soustraire :',a-5)
print('Multiplier :',a*5)
print('Diviser :',a/5)
print('Puissance :',a**2)
print('Reste :',a%5)

Soustraire : [-4 -3 -2 -1  0]
Multiplier : [ 5 10 15 20 25]
Diviser : [0.2 0.4 0.6 0.8 1. ]
Puissance : [ 1  4  9 16 25]
Reste : [1 2 3 4 0]


## Fonctions statistiques

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print('Somme de tout les éléments du tableau =' , A.sum()) # effectue la somme de tous les éléments du tableau
print('La somme des colonnes =' , A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print('La somme des lignes =', A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print('La somme cumulée =', A.cumsum(axis=0)) # effectue la somme cumulée

Somme de tout les éléments du tableau = 21
La somme des colonnes = [5 7 9]
La somme des lignes = [ 6 15]
La somme cumulée = [[1 2 3]
 [5 7 9]]


In [8]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('le produit des 2 vecteurs est = ', A.prod()) # effectue le produit
print('le produit accumulé =' , A.cumprod()) # effectue le produit cumulé

le produit des 2 vecteurs est =  720
le produit accumulé = [  1   2   6  24 120 720]


In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('la plus petite valeur du tableau =', A.min()) # trouve le minimum du tableau
print('la plus grande valeur du tableau =' , A.max()) # trouve le maximum du tableau
 
print('La moyenne = ' , A.mean()) # calcule la moyenne
print("l'écart type =" ,  A.std()) # calcule l'ecart type,
print('la variance du tableau =' , A.var()) # calcule la variance

la plus petite valeur du tableau = 1
la plus grande valeur du tableau = 6
La moyenne =  3.5
l'écart type = 1.707825127659933
la variance du tableau = 2.9166666666666665


On peut obtenir facilement l’index de la valeur minimale ou maximale dans le tableau le long d’un axe particulier à l’aide des méthodes argmin() et argmax():

In [10]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum le long d'une colonne
print('Min :',np.argmin(a,axis=0))
# maximum le long d'une ligne
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


## Algèbre linéaire

**numpy.dot(a, b, out=None)**
renvoie le produit des deux tableaux points par points

In [12]:
np.dot(3, 4)

12

In [13]:
a = [1, 0, 1]
b = [4, 2, 2]
np.dot(a, b)

6

In [6]:
a = [[1, 0], [2, 1]]
b = [[4, 1], [2, 5]]
np.dot(a, b)

array([[ 4,  1],
       [10,  7]])

##### **numpy.matmul** retourne le produit matriciel de deux tableaux.

In [27]:
a = np.array([[1, 3],
              [4, 1]])
b = np.array([1, 2])
np.matmul(a, b)

array([7, 6])

## Fonctions logiques

**all**

Teste si tous les éléments du tableau le long d'un axe donné valent True.

**any**

Teste si un élément du tableau le long d'un axe donné vaut True.

In [28]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

In [29]:
np.all([[True,False],[True,True]], axis=1)

array([False,  True])

In [30]:
np.any([[True, False], [True, True]])

True

## Diffusion
La diffusion fait référence à un ensemble de règles permettant d'appliquer une opération (qui ne s'applique normalement qu'à une seule valeur) à tous les éléments d'une table NumPy. Par exemple, pour des tableaux de même taille, des opérations telles que l'addition s'appliquent normalement élément par élément.

In [32]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])